### ISSUE TITLE
Change "What are some pros and cons of doing this?" to two seperate questions

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#104]
### What problem were you having?

In the Feature Request Issue Template, it has one question for both pros and cons.

### What solution would you like?

Add two seperate questions, one being "What are some pros of doing this?" and the other being "What are some cons of doing this?"

### What alternatives have you considered?

*No response*

### What are some pros and cons of doing this?

wait-

#### Pros:
- Easier to answer
- Looks better

#### Cons:
- Another question to answer

### Preview of how it would look after submission:

![image](https://github.com/Mesure73L/mesure.x10.mx/assets/115181664/0b683163-a98e-47be-9ac8-17e5e52559a7)

### What page is this for?

Repository

**Comment by Mesure73L** [comment]
What do you think @BeepBot99?

**Comment by BeepBot99** [comment]
You can do this.

**Comment by Mesure73L** [comment]
I will do this.

**Comment by BeepBot99** [comment]
THAT'S
LITERALLY
WHAT
I
JUST
SAID
YOU
FUCKING
IDIOT
