### ISSUE TITLE
Protect main branch so develop is never behind main

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#116]
### What problem were you having?

The `develop` branch has commits ahead of (which is fine) and behind (which is NOT fine) the `main` branch.

### What solution would you like?

Don't allow **anything** to be merged into `main` without being merged into `develop` first.

### What alternatives have you considered?

Just be smart to avoid conflicts.

#### Pros:

- Makes it easier to merge releases
- Avoids merge conflicts which will inevitably delay the process
- Easier to manage the branches

#### Cons:

- You will have to release everything at once
- Might get complicated if multiple things are being worked on at once (could be avoided by using branches for literally everything, as we currently are)
- Version control could get a bit more complicated

### What page is this for?

Repository

**Comment by BeepBot99** [comment]
No, it is fine how it is, because as long as you merge main into develop after you make any commits to main, it will be fine.

**Comment by Mesure73L** [comment]
But what if you're working on something in `develop`, like Twelve of Code, so you can't merge `main` into `develop`?

**Comment by BeepBot99** [comment]
Now, develop is not behind main anymore.

**Comment by BeepBot99** [comment]
I don't think you fully understand how Git works.
It only merges changes.
If you merge main into develop and are working on Twelve of Code, it will not merge main's Twelve of Code because it has not changed.

**Comment by Mesure73L** [comment]
> I don't think you fully understand how Git works.

Nah, really?

> It only merges changes. If you merge main into develop and are working on Twelve of Code, it will not merge main's Twelve of Code because it has not changed.

I forgot about that, mb

**Comment by Mesure73L** [comment]
This is not completed. If you close an issue, please mark it correctly.
