### ISSUE TITLE
Twelve of Code on main branch is not loading

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#118]
### What happened?

![image](https://github.com/Mesure73L/mesure.x10.mx/assets/115181664/b167ae3f-5c2d-4351-b67e-c0e75cfde0e0)

### What did you expect to happen?

I expected it to load.

### What page was this on?

Twelve of Code

### What browser(s) were you experiencing this on?

Google Chrome (desktop)

**Comment by BeepBot99** [comment]
It doesn't matter. It is the main branch. When develop is merged into main, it will all be fine.
