### ISSUE TITLE
Clicking on years doesn't change the hash

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#119]
### What happened?

Clicking on months and challenges changes the hash to the correct one, but clicking on a year does nothing.

### What did you expect to happen?

It changes the hash to the correct hash when clicking on a year

### What page was this on?

Twelve of Code

### What browser(s) were you experiencing this on?

Google Chrome (desktop), Other (Please specify)

**Comment by Mesure73L** [comment]
I will look into it, it worked before merging, we probably accidentally removed the code while resolving the conflicts.

**Comment by Mesure73L** [comment]
I fixed the problem, we used the wrong `createDOMYears()` or some part of it when resolving the conflicts.

## Explanation

Lines 470-472 had this code:
```js
yearElement.addEventListener("click", () => {
    yearSelect(year);
});
```

What I did is I changed `yearSelect(year)` to `yearSelect(year, true)` to make it change the hash.

---

This is still not completed yet as I found another bug with the month selector. I will commit it all once it's done.
