### ISSUE TITLE
Remove "Code of Conduct applies" from bug report issue template

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#120]
### Issue Contents

Remove where it says "Code of Conduct applies," because it already says it lower.
![image](https://github.com/Mesure73L/mesure.x10.mx/assets/74377508/4d3ad81a-90f3-41fa-8954-f6161e73de82)

**Comment by Mesure73L** [comment]
The gray text is not as visible and most people would skip past it.

**Comment by Mesure73L** [comment]
Not really. It is in an awkward place and most people would ignore the fine print anyways.
