### ISSUE TITLE
Remove the space in the Twelve of Code license

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#124]
### Issue Contents

![image](https://github.com/Mesure73L/mesure.x10.mx/assets/115181664/fb449bf7-eb44-4c13-9a01-06b44645f167)

**Comment by BeepBot99** [comment]
Why can't you just do it? It is really simple.

**Comment by Mesure73L** [comment]
I was not the one who caused that to happen.

**Comment by BeepBot99** [comment]
Yes, you were. You put it in. I have never touched it. Please don't blame me.

**Comment by Mesure73L** [comment]
Uhhhhhhhhh so uhmmmm
I had the icons there, and then suddenly they were replaced with a space.
I never removed the icons. I remember you saying you didn't like them.

**Comment by Mesure73L** [comment]
I'm not blaming you, I'm saying that I don't want to fix it because I didn't put it there.

**Comment by BeepBot99** [comment]
Yeah, I didn't like them.
A few weeks ago, I saw that they were gone, and I was surprised.
I also noticed the empty space.
I tried to remove it, but I couldn't figure out how, so I just gave up.
