### ISSUE TITLE
Fix this happening with Netlify whatever

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#125]
### Issue Contents

![image](https://github.com/Mesure73L/mesure.x10.mx/assets/115181664/77e90eed-2ebc-4541-a517-12fd4728932c)

**Comment by Mesure73L** [comment]
Notifications 🤯

**Comment by Mesure73L** [comment]
Oh right you're too dumb to understand
https://github.com/notifications

**Comment by BeepBot99** [comment]
We get different notifications.
# 🤯

**Comment by BeepBot99** [comment]
Yes, but I didn't get those notifications.

**Comment by Mesure73L** [comment]
Skill issue.

**Comment by Mesure73L** [comment]
I would still like this to be fixed.

**Comment by BeepBot99** [comment]
Check the newest pull request.

**Comment by BeepBot99** [comment]
And it is your issue that you get a notification for **every single workflow run**.

**Comment by Mesure73L** [comment]
It isn't. It's the hub's issue.
