### ISSUE TITLE
Netlify is blocked for me

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#130]
### Issue Contents

Yeah so like 5 minutes ago it became blocked so yeah just letting you know I can't really develop or review at school anymore

**Comment by BeepBot99** [comment]
Whenever someone views a site that hasn't been viewed a lot, the district checks it and usually blocks it as a "security threat."

**Comment by Mesure73L** [comment]
L

**Comment by Mesure73L** [comment]
skill issue

**Comment by Mesure73L** [comment]
imagine having a smart school district

**Comment by BeepBot99** [comment]
Imagine not

**Comment by Mesure73L** [comment]
Also things like this should always be put in **discussions**.
Issues are for problems, like bugs in the code. Not stupid stuff that we can't control.

**Comment by Mesure73L** [comment]
> Imagine not

...being able to code/review in school
Big
# L

**Comment by Mesure73L** [comment]
We're still setting up Netlify previews for the other pages (Main Site, Blog, and Projects)

**Comment by BeepBot99** [comment]
Well we don't really need to anymore right?

**Comment by BeepBot99** [comment]
It doesn't help anyone.
You have GHCS.

**Comment by Mesure73L** [comment]
It's easier to do that than to use GHCS.

**Comment by Mesure73L** [comment]
Also wouldn't it be easier for you when you're at home?

**Comment by Mesure73L** [comment]
Plus GHCS has limited hours. I want to save them for actual development and things I need GHCS to do.

**Comment by Mesure73L** [comment]
Wait I found a solution

**bring your laptop to school**

ever thought of that?

**Comment by BeepBot99** [comment]
I'm not allowed to use the WIFI.

**Comment by BeepBot99** [comment]
WAIT A MINUTE BREAKING NEWS

**Comment by BeepBot99** [comment]
Netlify is not blocked.
Only your website is because it detected something.

**Comment by BeepBot99** [comment]
So yeah haha.

**Comment by Mesure73L** [comment]
WHAT

WHAT DID IT DETECT BRO

**Comment by Mesure73L** [comment]
wait so then

it has to be something on twelve of code

WHAT IS IT DETECTING

**Comment by Mesure73L** [comment]
> I'm not allowed to use the WIFI.

s
t
a
r
l
i
n
k

**Comment by Mesure73L** [comment]
or just get mobile data and use it on your computer

**Comment by BeepBot99** [comment]
Mobile data...
On what phone?

**Comment by Mesure73L** [comment]
ON YOUR COMPUTER
READ IT

**Comment by BeepBot99** [comment]
Starlink how?
You want me to put a sattelite on top of my school?

**Comment by BeepBot99** [comment]
Also I don't want to support Elon Musk.

**Comment by Mesure73L** [comment]
**or mobile data**

# `🤯`

**Comment by BeepBot99** [comment]
It's grayed out in settings.

**Comment by Mesure73L** [comment]
maybe cause you dont have the correct equipment

SO GET THE CORRECT EQUIPMENT

**Comment by BeepBot99** [comment]
What equipment do I need?
I'm not paying for anything.
# 🤯

**Comment by BeepBot99** [comment]
Wait no
it says "Blocked by your administrator"

**Comment by Mesure73L** [comment]
Wait
THEY SPECIFICALLY BLOCKED 12OC???
