### ISSUE TITLE
Light mode for Twelve of Code

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#131]

**Comment by BeepBot99** [comment]
We need light mode because a lot of people (just not me or you though) prefer to use light mode over dark mode.

**Comment by Mesure73L** [comment]
What programmer likes light mode?

**Comment by Mesure73L** [comment]
> Highlights: The Most Important Statistics. As of 2020, 92% of software developers prefer dark mode for their integrated development environment. In 2020, 81.9% of developers prefer dark mode over light mode while coding.
Source: https://zipdo.co/statistics/dark-mode-usage/

**Comment by Mesure73L** [comment]
> [This poll asked](https://css-tricks.com/new-poll-light-on-dark-or-dark-on-light/) people if they like their code editor colors “dark code on light background” or “light code on dark background.” Turns out about 2/3 of people prefer light code on dark background.

Source: https://css-tricks.com/poll-results-light-on-dark-is-preferred/

**Comment by Mesure73L** [comment]
> According to a survey, 70% of software engineers prefer a Dark theme IDE over the light theme. You will always a lot of dark theme in the popular theme section of any IDE.

Source: https://dev.to/surajondev/why-most-developers-prefer-the-dark-theme-ide-1ml7

**Comment by Mesure73L** [comment]
In addition, Advent of Code (which many professional programmers compete in) has only one theme: dark theme.

**Comment by Mesure73L** [comment]
I'll reopen this if I think we should make it. Will not be in release 1.0.0.

**Comment by BeepBot99** [comment]
I'm not saying that a lot of software developers use light mode.
I'm just saying that the people who do use light mode might not do 12oC if it's in dark mode.
The reason I am willing to do this even though I don't really care is because it wouldn't take that much effort. In addition, if I did this, I could make CSS custom properties for all of the colors (only if you want though).
8% of programmers preferring light mode over dark mode is not a lot, but it is still 2 out of every 25.
