### ISSUE TITLE
Remove info label.

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#135]
### Issue Contents

The description of the `info` label is this:
> Information related to this repo

The description of the `repository` label is this:
> Related to this repository or related projects

The description of the `wiki` label is this:
> Related to this repository's Wiki

(No idea why it's capitalized)

Everything that will fall under the `info` label will also always fall under either the `repository` label or the `wiki` label, so there is no need for the `info` label.
Therefore, I suggest that we remove it.

**Comment by Mesure73L** [comment]
`info` is for general information and can be applied even when not relevant to the repository or wiki.
