### ISSUE TITLE
Twelve of Code data input doesn't work

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#15]
Mostly just a to-do but the Twelve of Code data input is disabled and needs to be programmed
![image](https://github.com/Mesure73L/Mesures-Website/assets/115181664/57fc30e3-295f-47e4-b2fb-e6ec60635574)

- [x] Get Export Data working
- [x] Get Import Data working

**Comment by BeepBot99** [comment]
Why is that a problem? Can't you just make it not disabled?

**Comment by Mesure73L** [comment]
> Why is that a problem? Can't you just make it not disabled?

The JS code doesn't work

**Comment by Mesure73L** [comment]
ok i'll do it

**Comment by BeepBot99** [comment]
Please don't do it yet.
I need to rewrite the JavaScript first to use `CookieManager`, and we don't want to have to resolve complicated conflicts.

**Comment by Mesure73L** [comment]
in the future dont assign me until when it should be done

**Comment by BeepBot99** [comment]
Well, I didn't know that I would be creating `CookieManager` when I assigned you.

**Comment by Mesure73L** [comment]
ok

**Comment by BeepBot99** [comment]
So should the user be able to enter data into the `<textarea>`?

**Comment by Mesure73L** [comment]
Correct, but make sure to verify that it is valid data before changing the cookies

**Comment by BeepBot99** [comment]
OK

**Comment by BeepBot99** [comment]
Can I use [this library](https://sweetalert2.github.io/) to give an error message if the settings data is invalid?

**Comment by Mesure73L** [comment]
> Can I use [this library](https://sweetalert2.github.io/) to give an error message if the settings data is invalid?

Yes, please also update the other settings inputs to use that library also for consistency purposes

**Comment by BeepBot99** [comment]
OK, sure!
Are there any rules about what the username and seed can be?
For example, only numerical or only alphanumueric?

**Comment by Mesure73L** [comment]
> OK, sure! Are there any rules about what the username and seed can be? For example, only numerical or only alphanumueric?

Username can be anything, seed has to be a number between `1000000000` and `9999999999` (any 10 digit number that does not start with a 0)

**Comment by BeepBot99** [comment]
Ok, there's one slight problem, but it probably doesn't matter.
The people who made SweetAlert2 really don't like Russia because of the war.
So, they made their software "protestware."
Whenever you use your website in Russia, it will block all navigation and play the national anthem of Ukraine.

**Comment by Mesure73L** [comment]
> Ok, there's one slight problem, but it probably doesn't matter. The people who made SweetAlert2 really don't like Russia because of the war. So, they made their software "protestware." Whenever you use your website in Russia, it will block all navigation and play the national anthem of Ukraine.

okay, what?

**Comment by BeepBot99** [comment]
What's your question?

**Comment by BeepBot99** [comment]
If a user from Russia tries to access your website, they won't be able to.
Because the person who made the library is Ukranian and so put that into the code.

**Comment by BeepBot99** [comment]
All pointer events will be blocked and the Ukranian national anthem will be played.

**Comment by Mesure73L** [comment]
> What's your question?

its not really a question

**Comment by Mesure73L** [comment]
Look for another library but if you can't find anything use it (or make your own)

**Comment by BeepBot99** [comment]
All other libraries have one of the following:
- Haven't been updated for 5 years
- Very **very** bad reviews
- <0% customizability
On all blog posts about it, SweetAlert2 is the best.
I don't think you'll have any users from Russia, so I'll just use it.

**Comment by Mesure73L** [comment]
Does [React-Toastify](https://github.com/fkhadra/react-toastify#readme) have what you want?

**Comment by BeepBot99** [comment]
OK, I will use it then.

**Comment by Mesure73L** [comment]
When do you think this will be completed?

**Comment by BeepBot99** [comment]
I haven't had a lot of time to work on it.
I will have ~1.5 hours today. I probably will finish it today, but if not, then it will probably be done on Saturday.

**Comment by BeepBot99** [comment]
- [ ] Get Export Data working
- [ ] Get Import Data working
