### ISSUE TITLE
SeedManager Class

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#162]
### Issue Contents

@Mesure73L I have created a `SeedManager` class. It works as follows, on a **per challenge basis**. This means that for each challenge, you have a seperate instance of `SeedManager`.
Here is an example that will hopefully show you how it works:
```js
const sman /*superman maybe???*/ = new SeedManager(
  029340, // seed
  ["appleType", "pearType"] // names of random values needed for the challenge
);
```
Then, you can access things like `sman.appleType` and `sman.pearType`. Each is a random number in between 0 and 1, just like random numbers generated by `Math.random()`. However, it will be the same every time **for a given seed.** For example, with the seed `029340`, `sman.appleType` and `sman.pearType` will be the same every time, but they will be a different pseudorandom number if it is a different seed.
# Here is my question:
Can I please make the seed able to be any string? I have a hash function to convert it to a number. That way, it would give the user more customizability.

**Comment by Mesure73L** [comment]
> Can I please make the seed able to be any string? I have a hash function to convert it to a number. That way, it would give the user more customizability.

Why do you need that

**Comment by BeepBot99** [comment]
I don't, it would just be nice. Also, why can't it start with a 0? You understand like no group theory.

**Comment by Mesure73L** [comment]
The seed is a number between 1000000000-9999999999

**Comment by BeepBot99** [comment]
I know, why not 0?

**Comment by BeepBot99** [comment]
And why not any string?

**Comment by Mesure73L** [comment]
> I know, why not 0?

Fine

> And why not any string?

BECAUSE NUMBER ≠ TEXT

**Comment by BeepBot99** [comment]
Yeah, I'm saying what's the problem with making it so it can accept text?

**Comment by BeepBot99** [comment]
You can easily do that by using a good hashing function.

**Comment by Mesure73L** [comment]
No text

**Comment by BeepBot99** [comment]
Yes, I'm asking why.

**Comment by Mesure73L** [comment]
Because i dont want it

**Comment by BeepBot99** [comment]
## Pros of having a hashing function
* Tiny changes in the seed make a big difference in the challenges. If a challenge is too hard with the current seed, and you want to try a new seed, you might just change one digit. That will not change the challenge by that much. However, if you have a hashing function, it will greatly change the challenge, and it will be almost indistinguishable from the old one.
* It allows for more creativity for your seed. You could do like, your name or your parents' names if you wanted to.
## Cons of having a hashing function
* I really don't know, I can't think of any, but apparently you have one.

If you can't give me an actual, good reason for why you don't want it, other than that you don't want it, then I am going to add it in my next commit.

**Comment by Mesure73L** [comment]
By the way, how can I access `CookieManager` in the challenge file?

**Comment by BeepBot99** [comment]
No, I'm asking for a valid reason. If you're just going to completely ignore me without any valid reasoning, then I am going to do it.

**Comment by BeepBot99** [comment]
And if you're not going to give me a valid reason, I don't care what you say then.

**Comment by Mesure73L** [comment]
You are still not allowed to say that, this is supposed to be constructive not forced.

**Comment by Mesure73L** [comment]
> fine

and did you even read what was before that?

**Comment by BeepBot99** [comment]
> You are still not allowed to say that, this is supposed to be constructive not forced.

Yes, so if you are not going to provide any valid reasoning, I am going to say it.

**Comment by Mesure73L** [comment]
> > fine
> 
> and did you even read what was before that?

.

**Comment by BeepBot99** [comment]
I did realize.

**Comment by Mesure73L** [comment]
X for doubt

**Comment by BeepBot99** [comment]
Thank you!

**Comment by Mesure73L** [comment]
Exactly, you are agreeing to me saying that I disagree with you. wait-
