### ISSUE TITLE
Update the ToS for Challenge Packs

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#172]
### Issue Contents

When creating functionality for challenge packs, update the ToS to state that all content must be appropriate and nonviolent. You've made all the other documents like this, so I am assigning you.

**Comment by Mesure73L** [comment]
We will have a ToS for the in-app database, but if someone wants to make something else and not publish it or publish it somewhere else then that's fine. We can add a note saying custom challenge packs that aren't in the database are third-party content and may not be SFW.

**Comment by BeepBot99** [comment]
No, I don't think any coding challenge should be NSFW. I think we should say that if we find a challenge that is NSFW, we will ban the domain from ever creating them again (unless ofc it is like GitHub or something, then we will ban the user.)

**Comment by Mesure73L** [comment]
That's why we will create an in-app database to allow people to find extra SFW challenges. Blacklisting a domain doesn't really do anything though, because someone can just fork the repo and remove their domain from the blacklist.

**Comment by Mesure73L** [comment]
I do not like the idea of monitoring third-party content that is never mentioned on this repo or mentioned with a very noticable warning.

**Comment by BeepBot99** [comment]
> Blacklisting a domain doesn't really do anything though, because someone can just fork the repo and remove their domain from the blacklist.

Yes, but then it wouldn't be allowed in https://mesure.x10.mx/twelve-of-code. I think that it shouldn't be allowed in https://mesure.x10.mx/twelve-of-code. I don't think it's appropriate to have NSFW challenges on the website hosted by this repo. Our coding environment should be safe for everyone. If someone wants NSFW coding challenges elsewhere, they can do that, but they shouldn't be able to do that here.

**Comment by Mesure73L** [comment]
> Yes, but then it wouldn't be allowed in https://mesure.x10.mx/twelve-of-code. I think that it shouldn't be allowed in https://mesure.x10.mx/twelve-of-code. I don't think it's appropriate to have NSFW challenges on the website hosted by this repo. Our coding environment should be safe for everyone. If someone wants NSFW coding challenges elsewhere, they can do that, but they shouldn't be able to do that here.

It will not be on the website. It will be third-party user-created content, which I will not be controlling. This is the reason why we will have an official database of SFW challenges and say that if you are importing it from a URL, we cannot guarantee the safeness nor security of the challenges and you should use them at your own risk.
