### ISSUE TITLE
Make 12oC Mobile Responsive

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#40]
### What problem were you having?

It's not mobile responsive

### What solution would you like?

Make it mobile responsive

### What alternatives have you considered?

Be a dickhead

### What are some pros and cons of doing this?

Pros: everything
Cons: nothing

### What page is this for?

Twelve of Code

**Comment by Mesure73L** [comment]
Please be more serious when making bug reports in the future - we ask the questions for a reason and we need the information.

For the mobile responsiveness, why would you be doing a coding challenge on your phone?

**Comment by BeepBot99** [comment]
OK, I will answer them seriously in the future.
However, it is kind of obvious.
Anyway, you might not do the coding challenges on your phone, but you might want to check out the website and see what it is about.
90% of times a website is viewed is from mobile.
You don't want to miss out on 90% of your customers.
Also, if you want to, you could add ads.
Look at Google Adsense.
You could do the ones that pop up when you click a link and you click continue.

**Comment by Mesure73L** [comment]
Create another issue for ads.
You can do mobile support.

**Comment by Mesure73L** [comment]
This isn't really a bug.

**Comment by BeepBot99** [comment]
You can do what you want, but I classified it as a bug because it doesn't appear as expected on mobile.

**Comment by Mesure73L** [comment]
A bug is something that we coded that has a problem/glitch. Since there was no previous mobile version made, it is not a bug.

**Comment by BeepBot99** [comment]
Why did you unassign me?
Backlog is for things that are assigned but might not happen.
