### ISSUE TITLE
Rename "fixed" label to "completed"

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#50]
### What problem were you having?

It doesn't make sense for some issues because not all issues are bugs or problems.

### What solution would you like?

Rename the "fixed" label to "completed"

### What alternatives have you considered?

Keep the label as "fixed"

### What are some pros and cons of doing this?

Pro - Makes more sense
Con - idk

**Comment by BeepBot99** [comment]
Personally, I like fixed a little better.
Maybe have both?

**Comment by Mesure73L** [comment]
That would be a duplicate, I'm renaming it
