### ISSUE TITLE
Github project for 12oc

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#51]
### What problem were you having?

hard to manage issues

### What solution would you like?

make a project

### What alternatives have you considered?

keep it as it is

### What are some pros and cons of doing this?

pros: easier to manage
cons: more moderation required

### What page is this for?

Twelve of Code

**Comment by Mesure73L** [comment]
Maybe

**Comment by BeepBot99** [comment]
If we do this, then, when there is an issue for everything needed to be done, you will be able to drag and drop issues like this:
![image](https://github.com/Mesure73L/mesure.x10.mx/assets/74377508/8243b1ca-b00c-4525-bfd4-2affea6a9438)
You will also be able to put expected completion dates and merge dates on a calendar, which would be nice.
It is all about time management.

**Comment by Mesure73L** [comment]
What should the project name be?

**Comment by BeepBot99** [comment]
`Twelve of Code Release #1`

**Comment by Mesure73L** [comment]
Please remake the paused category.

**Comment by BeepBot99** [comment]
I will finish this by tomorrow, hopefully by today.
> Please remake the paused category

The reason I deleted it is because I am working on automating it.
I did not permenantly delete it.
I am just going to show it in a different way.

**Comment by BeepBot99** [comment]
Merging #61 into this.

**Comment by BeepBot99** [comment]
Unmerging #61.
