### ISSUE TITLE
Automatically add pending to feature request issues

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#52]
### What problem were you having?

I have to add it manually

### What solution would you like?

Add it automatically

### What alternatives have you considered?

Have to add it manually

### What are some pros and cons of doing this?

Pro: less work
Con: You might not always want it, but you usually will

**Comment by Mesure73L** [comment]
Kinda supposed to be a "maybe" mentioned in #44

**Comment by Mesure73L** [comment]
You can rename it if you want
