### ISSUE TITLE
Issue template for 12oc challenge suggestion

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#53]
### What problem were you having?

There is no template in the discussion, and I like templates.

### What solution would you like?

Make an issue template for it. I can make it if you want. It could have like theme, explanation, details or something like that

### What alternatives have you considered?

Just do it in the discussion.

### What are some pros and cons of doing this?

Pro: there is a template
Pro: easier to manage issues than discussions
Con: in issues instead of discussions, may clutter it up, may not.

### What page is this for?

Twelve of Code

**Comment by Mesure73L** [comment]
For now use discussions
