### ISSUE TITLE
Create an issue for everything needed for 12oC

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#54]
### Issue Contents

That way, we can see an accurate percentage for how completed it is.

**Comment by Mesure73L** [comment]
We can work together on this

**Comment by BeepBot99** [comment]
Okay, thank you.

**Comment by BeepBot99** [comment]
@Mesure73L Hi, is this still happening?
Just wanted to make sure.

**Comment by Mesure73L** [comment]
Yes
