### ISSUE TITLE
Please add more contrast to the 12oc 1.0.0 project priorities list

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#63]
### Issue Contents

![image](https://github.com/Mesure73L/mesure.x10.mx/assets/115181664/dfda9922-4485-45be-b29f-eab709534c17)

Please change the colors at the top (in the circle), the medium and high look exactly the same to me.
Suggestions (if custom is possible, low medium high): `#00de24`, `#dcd100`, `#f70000`

**Comment by Mesure73L** [comment]
Ok

**Comment by BeepBot99** [comment]
By the way, don't add it to the project. Adding the twelve-of-code label will automatically add it to the project.

**Comment by Mesure73L** [comment]
Either a darker green or darker yellow could make it a bit better, if not thats fine

**Comment by BeepBot99** [comment]
Done!

**Comment by Mesure73L** [comment]
Thank you
