### ISSUE TITLE
Create hashes for 12oC challenges

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#64]
### What solution would you like?

A way to put like `#2023-dec-1` at the end of the URL to open the page on that challenge would be nice.

### What alternatives have you considered?

`?challenge=20231201` or something (2023, 12, 01)

#### Pros
- Easier to share challenges that you enjoyed
- Faster to load onto a challenge

#### Cons
- IDK

### What page is this for?

Twelve of Code

### What needs to get done?

- [x] Automatically set the challenge to be active and load it on page load
- [x] Change the URL when a challenge is loaded
- [x] Detect when the URL is changed to allow users to type in the URL
- [x] Verify that the challenge is released and existent when attempting to load it
- [ ] Fix all bugs
- [ ] Add Wiki docs explaining how to use it (not required for completion)

**Comment by BeepBot99** [comment]
Totally! A few questions though:
* When selecting a challenge, will it automatically change the URL to go to that page?
* Are you doing this or am I?

**Comment by Mesure73L** [comment]
> When selecting a challenge, will it automatically change the URL to go to that page?

Yes, that's what I'm hoping for.

**Comment by BeepBot99** [comment]
You could do this.
https://www.30secondsofcode.org/js/s/modify-url-without-reload/

**Comment by Mesure73L** [comment]
> You could do this. https://www.30secondsofcode.org/js/s/modify-url-without-reload/

Should be 30 of Code. /j

**Comment by Mesure73L** [comment]
Not merged yet
