### ISSUE TITLE
Change the "Report a bug" link to go to the template chooser

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#65]
### What happened?

Current text: Report a bug on [the GitHub page](https://github.com/Mesure73L/My-Website/issues/new).
What happened when I clicked the link: Went to the old issue creation thing.

### What did you expect to happen?

Expected either bug report or template chooser.

### What page was this on?

Twelve of Code

### What browser(s) were you experiencing this on?

Google Chrome (desktop)

**Comment by BeepBot99** [comment]
Okay, go to this link then instead:
https://github.com/Mesure73L/mesure.x10.mx/issues/new?assignees=&labels=bug&projects=&template=1-bug-report.yml

**Comment by Mesure73L** [comment]
> Okay, go to this link then instead: https://github.com/Mesure73L/mesure.x10.mx/issues/new?assignees=&labels=bug&projects=&template=1-bug-report.yml

I'm gonna make it go to the template chooser, I want it to be clear that security vulnerabilities should be reported privately & outside of issues
