### ISSUE TITLE
Name of "Development Paused" View

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#71]
### Issue Contents

It should not be development paused because it includes these things:
* Ready
* Backlog
* Todo
* Paused

Only one of those is paused.

**Comment by Mesure73L** [comment]
"Not Under Active Development" is way too long tho

**Comment by BeepBot99** [comment]
I know but I don't know what else to do.

**Comment by Mesure73L** [comment]
What's the point of it?

**Comment by Mesure73L** [comment]
the view

**Comment by BeepBot99** [comment]
The only other way is in all items

**Comment by Mesure73L** [comment]
> To see paused things

SO NAME IT DEVELOPMENT PAUSED

**Comment by BeepBot99** [comment]
And in pull requests

**Comment by BeepBot99** [comment]
But for paused issues

**Comment by BeepBot99** [comment]
And then backlog used to be needed there too

**Comment by BeepBot99** [comment]
I could just add paused to the features view

**Comment by BeepBot99** [comment]
Should I do that?

**Comment by Mesure73L** [comment]
can you just write it in one message

**Comment by BeepBot99** [comment]
I

**Comment by Mesure73L** [comment]
> I could just add paused to the features view

sure

**Comment by BeepBot99** [comment]
N

**Comment by BeepBot99** [comment]
E

**Comment by Mesure73L** [comment]
By the way, I created a new project. Please do whatever you need to do in that

**Comment by BeepBot99** [comment]
By the way, you can only see things with the milestone now.
Everything else is only visible in calendar and all items.

**Comment by BeepBot99** [comment]
This is done.
