### ISSUE TITLE
Other project for this repository

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#72]
### Issue Contents

I created the new project. Please manage it and do all of that stuff. https://github.com/users/Mesure73L/projects/3

**Comment by BeepBot99** [comment]
What should the name for it be?
Mesure's Website maybe

**Comment by Mesure73L** [comment]
> What should the name for it be? Mesure's Website maybe

Whatever you want

**Comment by BeepBot99** [comment]
And what issues should be automatically put there?

**Comment by Mesure73L** [comment]
> And what issues should be automatically put there?

Any issue that is given the `blog`, `projects`, or `main site` labels.

**Comment by BeepBot99** [comment]
And by the way you can write the readme and description.

**Comment by Mesure73L** [comment]
@BeepBot99 
**What should it be called?** `Mesure's Website` maybe
**What issues should be automatically put there? Only ones with main site, projects, and/or blog?** Correct, maybe make a new label called `website` or something
**Should it have milestones or not?** Yes
**Should it have a variable for what site it is on?** Sure, that could be useful

**Comment by BeepBot99** [comment]
You can make the milestones.
Just make them in this repository.

**Comment by Mesure73L** [comment]
Ok

**Comment by Mesure73L** [comment]
I'll create them as we need

**Comment by BeepBot99** [comment]
Right now, it will show every issue.
If you want me to make it only show issues from a certain milestone like in 12oC, just tell me.

**Comment by BeepBot99** [comment]
I'll work on it later, please don't do anything in it right now.

**Comment by BeepBot99** [comment]
Done.

**Comment by BeepBot99** [comment]
Note that you have to change the website variable manually, there is no way to automate it without paying.

**Comment by Mesure73L** [comment]
Ok
