### ISSUE TITLE
Need a plan for releasing challenges

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#75]
### Issue Contents

Right now, we will have to manually go in and update `information.json`. Is there any better way to do this, that doesn't involve manually updating it?

### Steps

- [x] Think of a solution
- [x] Program that solution

**Comment by BeepBot99** [comment]
What do you mean updating information.json? Do you mean making a challenge released?
If so, we could instead of released, put a time in information.json and make it release automatically at that time. We could also add a timer until the next challenge if we wanted to.

**Comment by Mesure73L** [comment]
Can you make it either `true`, `false`, or an epoch unix timestamp?

**Comment by BeepBot99** [comment]
Sure, although I don't understand why we can't only have a timestamp, but whatever.

**Comment by Mesure73L** [comment]
I want the option to set it to `true` or `false` also so if we need to enable a challenge for development we can.

**Comment by BeepBot99** [comment]
OK.
