### ISSUE TITLE
Remove priorities view

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#76]
### What problem were you having?

There are too many ways to change the priority.
For example, the priorities view, my tasks, all items, calendar, or by just opening an issue and changing it on the right side.

### What solution would you like?

Remove the priorities view

### What alternatives have you considered?

Keep it and have too many ways (in my opinion)

### What are some pros and cons of doing this?

Pros: less complicated
Cons: more complicated (kind of)

### What page is this for?

Twelve of Code

**Comment by Mesure73L** [comment]
We should keep the priorities view, it allows us to see it in a different way. Plus those different ways to change it are all synced, so I don't see the problem with it.
