### ISSUE TITLE
Protected Branches + Website Previews

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#90]
### What solution would you like?

* Can't commit directly to the main branch, must always create a pull request
* All pull requests must be reviewed by someone else before being merged
* A temporary reviewing server will be created just for the pull request where you can preview the pull request before it is merged.
* You can't merge it before the preview website is created.

I have created all of that in https://github.com/beepbot99/testing-protected-branches.

### What alternatives have you considered?

Keep it as it currently is.

### What are some pros and cons of doing this?

I don't know.

### Additional Stuff

Please do not do this. Let me do this. I already did it in a testing repo.

### What page is this for?

*No response*

**Comment by BeepBot99** [comment]
I invited you to be a collaborator on the testing repo. Once you accept it, try committing directly to the `main` branch. In addition, try merging a pull request into the `main` branch. You will not be able to commit directly, and you will not be able to merge a pull request until the preview website has been created. I did not do the review thing because I am the only one working in the repository, so then no pull request would ever be able to be merged. In addition, try previewing the testing website that I set up.

**Comment by BeepBot99** [comment]
Tell me if you would like me to add this feature to this repository.

**Comment by Mesure73L** [comment]
Please do not select the "What site is this for?" options if not directly related to those specific pages on the website.

**Comment by BeepBot99** [comment]
## What I can do now
* Create the action to create a preview server every time a pull request is created
## What we need to vc to do
* Prevent direct commits to the `main` branch
* Force pull requests to have a review
* Prevent merging into the `main` branch before the preview website is created

**Comment by Mesure73L** [comment]
I can VC at 18:195ish.

**Comment by BeepBot99** [comment]
NOW IT'S THREE DIGITS!?

**Comment by BeepBot99** [comment]
21:15 right?

**Comment by BeepBot99** [comment]
And by that you mean 21:35.

**Comment by BeepBot99** [comment]
Is [this link](https://65bc7a6f6846f83bec986f5b--previewabc.netlify.app/) blocked for you?

**Comment by BeepBot99** [comment]
> Please do not select the "What site is this for?" options if not directly related to those specific pages on the website.

It is though. When pull requests are created to those sites, you will be able to preview those websites.

**Comment by Mesure73L** [comment]
> Is [this link](https://65bc7a6f6846f83bec986f5b--previewabc.netlify.app/) blocked for you?

Nope

**Comment by Mesure73L** [comment]
> 21:15 right?

> And by that you mean 21:35.

No, I mean 18:195.

**Comment by BeepBot99** [comment]
> > Is [this link](https://65bc7a6f6846f83bec986f5b--previewabc.netlify.app/) blocked for you?
> 
> Nope

Good, you will be able to view the previews then.

**Comment by BeepBot99** [comment]
Done.
