### ISSUE TITLE
Make a way to mark a challenge as in progress

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#91]
### What solution would you like?

Make a way to mark a challenge as completed

### What alternatives have you considered?

This is a to-do item that needs to be completed

### What are some pros and cons of doing this?

Input
```js
const pros = "makes it easier to tell what you've already done";
const cons = undefined;
console.log(`Pros:\n${pros}\nCons:\n${cons}`);
```
Output
```
Pros:
makes it easier to tell what you've already done
Cons:
undefined
```

### What page is this for?

Twelve of Code

**Comment by BeepBot99** [comment]
What do you mean by marking a challenge as completed?
Do you mean building a UI on the website where you can check off challenges even if you have not completed them in that instance of the website?

**Comment by BeepBot99** [comment]
In the future, please be more specific with your issues.

**Comment by Mesure73L** [comment]
> What do you mean by marking a challenge as completed? Do you mean building a UI on the website where you can check off challenges even if you have not completed them in that instance of the website?

No, making a way to set a challenge as completed after the user finishes it and display it on the selector.

**Comment by Mesure73L** [comment]
And also telling the user using SWAL2 that they completed it.

**Comment by BeepBot99** [comment]
That already exists.
`cman.setChallengeStatus`
Look at the wiki.

**Comment by BeepBot99** [comment]
> And also telling the user using SWAL2 that they completed it.

I can do that.

**Comment by Mesure73L** [comment]
If there isn't already, make a way to mark a challenge as in progress. I might've said challenges aren't in progress before but now I think that some challenges might benefit from saving where you are in it.

**Comment by BeepBot99** [comment]
Well, currently the challenge can be one of these three:
1. `true`
2. `false`
3. An epoch time in milliseconds

So, I will make it so it can also be `"in progress"`.

**Comment by Mesure73L** [comment]
the user's cookies

**Comment by BeepBot99** [comment]
Oh yeah right
Well then `"in progress"`.

**Comment by Mesure73L** [comment]
There needs to be a third boolean value added.
`maybe`

`true`, `false`, or `maybe`
/j

**Comment by BeepBot99** [comment]
Have you heard of quantum computing?
Instead of a wire being off representing a 0 and on representing a 1, a wire can also be both off and on at the same time /srs.

**Comment by BeepBot99** [comment]
Also, George **Boole** studied **binary**, which is base **2**.

**Comment by Mesure73L** [comment]
Deleted those because clearly you don't know what "/j" means.
