### ISSUE TITLE
Twelve of Code should appear on the navbar with release 1.0.0

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#93]
### Issue Contents

With the official release of 1.0.0 on March 1, 2024, Twelve of Code should be added to the navbar.

**Comment by BeepBot99** [comment]
No, this should not be in the twelve of code project.

**Comment by Mesure73L** [comment]
It should still have the label

**Comment by BeepBot99** [comment]
It should be in to do, not ready. Ready is for unassigned things.

**Comment by Mesure73L** [comment]
> It should be in to do, not ready. Ready is for unassigned things.

I DONT CARE

**Comment by BeepBot99** [comment]
@Mesure73L Complete this now in the `develop` branch, because we will only be pushing `develop` to `main` when it releases.
