### ISSUE TITLE
Add an "all" option for website variable in Mesure's Website project

### ISSUE THREAD

**Issue by Mesure73L** [Mesure73L/mesure.x10.mx#94]
### Issue Contents

![image](https://github.com/Mesure73L/mesure.x10.mx/assets/115181664/59ef2862-970a-431b-ac33-2c2759d954d9)
There should be an "all" option. Maybe even a "repository" option. OR JUST REMOVE IT BECAUSE LABELS SAY THAT ANYWAYS!!!

**Comment by BeepBot99** [comment]
Sure I can remove it if you want.
I just thought it would be easier to manage.

**Comment by BeepBot99** [comment]
Done.
